extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  k8s_observer:
    auth_type: serviceAccount
    node: ${K8S_NODE_NAME}
  memory_ballast:
    size_in_percentage: 33
  basicauth/traces:
      client_auth:
        username: "${TRACES_USER_ID}"
        password: "${API_KEY}"
  basicauth/metrics:
      client_auth:
        username: "${METRICS_USER_ID}"
        password: "${API_KEY}"
  basicauth/logs:
      client_auth:
        username: "${LOGS_USER_ID}"
        password: "${API_KEY}"   

receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      processes:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 10s
    endpoint: ${K8S_NODE_IP}:10250
    extra_metadata_labels:
    - container.id
    metric_groups:
    - container
    - pod
    - node
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: otel-agent
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${K8S_POD_IP}:8889

processes:
  batch:
  filter/logs:
    logs:
      exclude:
        resource_attributes:
        # - key: splunk.com/exclude
        #  value: 'true'
  groupbyattrs/logs:
    keys:
    - container.id
    - fluent.tag
    - k8s.container.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.pod.uid
  resource/logs:
    attributes:
    # - action: upsert
    #   from_attribute: k8s.pod.annotations.splunk.com/sourcetype
    #   key: com.splunk.sourcetype
    # - action: delete
    #  key: k8s.pod.annotations.splunk.com/sourcetype
    # - action: delete
    #  key: splunk.com/exclude
  k8sattributes:
    extract:
      annotations:
      # - from: pod
      #   key: splunk.com/sourcetype
      # - from: namespace
      #   key: splunk.com/exclude
      #   tag_name: splunk.com/exclude
      # - from: pod
      #  key: splunk.com/exclude
      #   tag_name: splunk.com/exclude
      labels:
      - key: app
      metadata:
      - k8s.namespace.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - container.id
      - container.image.name
      - container.image.tag
    filter:
      node_from_env_var: K8S_NODE_NAME
    pod_association:
    - from: resource_attribute
      name: k8s.pod.uid
    - from: resource_attribute
      name: k8s.pod.ip
    - from: resource_attribute
      name: ip
    - from: connection
    - from: resource_attribute
      name: host.name
  memory_limiter:
    check_interval: 2s
    # limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resource:
    attributes:
    - action: insert
      key: k8s.node.name
      value: ${K8S_NODE_NAME}
    - action: insert
      key: k8s.cluster.name
      value: clusterName
  resource/add_agent_k8s:
    attributes:
    - action: insert
      key: k8s.pod.name
      value: ${K8S_POD_NAME}
    - action: insert
      key: k8s.pod.uid
      value: ${K8S_POD_UID}
    - action: insert
      key: k8s.namespace.name
      value: ${K8S_NAMESPACE}
  resourcedetection:
    detectors:
    - ec2
    - gce
    - azure
    - gke
    - eks
    - aks
    - env
    - system
    override: false
    timeout: 10s
  resource/add_environment:
    attributes:
    - action: insert
      value: ${ENVIROMENT}
      # value: production
      key: deployment.environment
  
  spanmetrics:
        metrics_exporter: grafana-prometheusremotewrite
exporters:
  grafana-tempo:
    endpoint: https://ingest.us0.signalfx.com/v2/trace
    tls:
          insecure: false
    authenticator: basicauth/traces
  grafana-loki:
    endpoint: https://ingest.us0.signalfx.com/v2/trace
    auth:
          authenticator: basicauth/logs
  grafana-prometheusremotewrite:
    endpoint: https://ingest.us0.signalfx.com/v1/log
    auth: basicauth/metrics
service:
  extensions:
  - basicauth/traces
  - basicauth/metrics
  - basicauth/logs
  - health_check
  - k8s_observer
  - zpages
  - memory_ballast
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      - kubeletstats
      - otlp
      processors:
      - memory_limiter
      - batch
      - resource
      - resourcedetection
      exporters:
      - grafana-prometheusremotewrite
    metrics/internal:
      receivers:
      - prometheus/internal
      processors:
      - memory_limiter
      - batch
      - resource
      - resource/add_agent_k8s
      - resourcedetection
      exporters:
      - grafana-prometheusremotewrite
    traces:
      receivers:
      - otlp
      - jaeger
      - zipkin
      processors:
      - memory_limiter
      - k8sattributes
      - batch
      - resource
      - resourcedetection
      - resource/add_environment
      exporters:
      - grafana-tempo
    logs:
      receivers:
      - fluentforward
      - otlp
      processors:
      - memory_limiter
      - k8sattributes
      - batch
      - groupbyattrs/logs
      - filter/logs
      - resource/logs
      - resource
      - resourcedetection
      - resource/add_environment
      exporters:
      - grafana-loki
