apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/grafana/
    repoURL: https://github.com/grafana/helm-charts/
    targetRevision: HEAD
    helm:
        valueFiles:
        - $values/apps/grafana/values.yaml
        - $values/apps/grafana/datasources.yaml
        - $values/apps/grafana/dashboards.yaml
      # parameters:
      #   # mode: "deployment"
      #   - name: mode
      #     value: "deployment"
        - repoURL: https://github.com/Cleanbeach/obs-apps.git
          path: apps/grafana/
          targetRevision: master
          ref: values
    # kräver absolut path
    # helm:
    #   valueFiles:
    #   - $values/apps/grafana/grafana-values.yaml
    #   - $values/apps/grafana/grafana-value-version.yaml
    #   - $values/apps/grafana/grafana-service.yaml
    
    
    #   - repoURL: https://github.com/Cleanbeach/obs-apps.git
    #   targetRevision: HEAD
    #   ref: values