# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/prometheus-community/helm-charts.git
#     targetRevision: 20.2.0
#     chart: charts/prometheus/
#   destination:
#    server: https://kubernetes.default.svc
#    namespace: default