apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/grafana/helm-charts/
      path: charts/grafana/
      targetRevision: HEAD
    - repoURL: https://github.com/Cleanbeach/obs-apps.git
      path: envs/dev/bet-obs-stack/apps/grafana/
      targetRevision: HEAD
      ref: values
    # helm:
    #     valueFiles:
    #     - $values/apps/grafana/values.yaml
    #     - $values/apps/grafana/deployment.yaml
    #     - $values/apps/grafana/persisten-volume-claim.yaml
    #     - $values/apps/grafana/datasources.yaml
    #     - $values/apps/grafana/dashboards.yaml
    #   # parameters:
    #   #   # mode: "deployment"
    #   #   - name: mode
    #   #     value: "deployment"
        