apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-stack-apps-in-apps
  namespace: argocd
  spec:
    source:
      repoURL: 'https://github.com/cleanbeach/obs-apps.git'
      path: envs/dev/bet-obs-stack/argocd/applications
    destination:
      namespace: argocd
      server: 'https://kubernetes.default.svc'
    project: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        limit: 3
  