apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    repoURL: https://github.com/Cleanbeach/obs-apps.git
    path: envs/dev/bet-obs-stack/apps/grafana
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
        