apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: envs/dev/apps/grafana
    repoURL: https://github.com/Cleanbeach/obs-apps.git
    targetRevision: HEAD